### ISSUE TITLE
CORS issues when trying to query measurments API and test files on S3

### ISSUE THREAD

**Issue by lislis** [TheTorProject/ooni-measurements#20]
Hey there @hellais, thanks for the awesome work on OONI!
I'm trying to build a simple web app with EmberJS that tries to query `https://measurements.ooni.torproject.org/api/v1/files` and then displays the results on a timeline filterable by country.
But I'm running into CORS issues when sending the request. Would it be possible to enable Cross Origin Headers for the measurements API?
Furthermore, I'm having the same troubles when trying to get the individual test results from S3. Maybe this is something that can be adjusted for public S3 buckets as well?
Thanks in advance!

**Comment by hellais** [comment]
Thanks for suggesting this.

Adding CORS headers to ooni-measurements should not be an issue. It seems like we can do the same thing for the [s3 buckets](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html#how-do-i-enable-cors).

That said having users of a site fetch the raw measurements from the s3 buckets can lead to them using a considerable amount of bandwidth, so you may want to consider if that is indeed what you want (keep in mind that some measurement files can be up to 70-80 MB).

I will update this ticket with details once it's implemented and deployed.

**Comment by hellais** [comment]
@anadahz can you redeploy production measurements with the latest master tip?

**Comment by anadahz** [comment]
@hellais shall we wait a  bit to see if everything work as expected on the staging server ([staging.measurements.ooni.io](http://staging.measurements.ooni.io))?

**Comment by hellais** [comment]
@anadahz I think you should proceed with deploying it. I have tested it locally and staging has been running for a day without issues.

**Comment by anadahz** [comment]
@hellais https://github.com/TheTorProject/ooni-sysadmin/pull/102

**Comment by anadahz** [comment]
Deployed https://github.com/TheTorProject/ooni-measurements/commit/b5921059b635df0984d2c242348c1562d880a698

**Comment by hellais** [comment]
This is done.

@lislis when you have something working for your app that uses OONI data we would love to hear back from you! 🎉

**Comment by lislis** [comment]
Thank you @hellais and @anadahz! I'll ping you once I have something showable 💃
